const S={opps:[],sup:[],fund:[],status:null};
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const fmt=d=>d?new Date(d+'T00:00:00').toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'}):'No deadline detected';
async function j(path,fallback){try{const r=await fetch(path+'?v='+Date.now());if(!r.ok)throw Error();return await r.json()}catch(e){return fallback}}
async function load(){[S.opps,S.sup,S.fund,S.status]=await Promise.all([j('reports/opportunities.json',[]),j('reports/supervisors.json',[]),j('reports/funding_routes.json',[]),j('reports/status.json',null)]);init()}
function init(){if(S.status?.checked_at)document.getElementById('lastScan').textContent='Last scan: '+new Date(S.status.checked_at).toLocaleString();stats();countries();opps();sup();fund();status()}
function stats(){const active=S.opps.filter(x=>x.status!=='expired'), high=active.filter(x=>x.research_fit>=75), confirmed=active.filter(x=>x.funding==='Confirmed');let v=[[active.length,'Active research matches'],[high.length,'High fit ≥75'],[confirmed.length,'Funded / salaried matches'],[S.status?.new_opportunities||0,'New this scan'],[S.sup.length,'Supervisors monitored'],[S.status?.sources_ok||0,'Sources reachable']];document.getElementById('stats').innerHTML=v.map(x=>`<div class="stat"><div class="num">${x[0]}</div><div class="lab">${x[1]}</div></div>`).join('')}
function countries(){const e=document.getElementById('country');[...new Set(S.opps.map(x=>x.country).filter(Boolean))].sort().forEach(c=>e.insertAdjacentHTML('beforeend',`<option>${esc(c)}</option>`))}
function opps(){const q=document.getElementById('search').value.toLowerCase().trim(),country=document.getElementById('country').value,f=document.getElementById('fundingFilter').value,theme=document.getElementById('themeFilter').value,st=document.getElementById('statusFilter').value,min=+document.getElementById('minFit').value;document.getElementById('minFitV').textContent=min;let xs=S.opps.filter(x=>{if(x.research_fit<min)return false;if(country&&x.country!==country)return false;if(f&&x.funding!==f)return false;if(st==='active'&&x.status==='expired')return false;if(st==='open'&&x.status!=='open')return false;if(theme==='paper1'&&x.paper1_score<x.paper2_score)return false;if(theme==='paper2'&&x.paper2_score<x.paper1_score)return false;if(theme==='bridge'&&Math.min(x.paper1_score,x.paper2_score)<45)return false;if(q&&!JSON.stringify(x).toLowerCase().includes(q))return false;return true}).sort((a,b)=>(b.is_new-a.is_new)||(b.strategic_score-a.strategic_score)||(b.research_fit-a.research_fit));document.getElementById('oppSummary').textContent=`Showing ${xs.length} of ${S.opps.length} detected research matches`;document.getElementById('oppList').innerHTML=xs.length?xs.map(oppCard).join(''):'<article class="card"><div>No matching research opportunity is currently detected under these filters.</div></article>'}
function oppCard(x){let chips=[];if(x.is_new)chips.push('<span class="chip new">NEW</span>');if(x.is_changed)chips.push('<span class="chip new">CHANGED</span>');if(x.stale)chips.push('<span class="chip">STALE / recheck pending</span>');chips.push(`<span class="chip">${esc(x.country)}${x.city?' · '+esc(x.city):''}</span>`);chips.push(`<span class="chip ${x.funding==='Confirmed'?'funded':''}">${esc(x.funding)} funding</span>`);if(x.status==='expired')chips.push('<span class="chip expired">Expired</span>');(x.keyword_hits||[]).slice(0,8).forEach(k=>chips.push(`<span class="chip">${esc(k)}</span>`));let amounts=(x.funding_amounts||[]).join(' · '),why=(x.why_match||[]).join(' | ');return `<article class="card"><div><h3>${esc(x.title)}</h3><div class="meta">${esc(x.university)} · ${esc(x.source)} · ${fmt(x.deadline)}${amounts?' · '+esc(amounts):''}</div><div class="chips">${chips.join('')}</div><div class="excerpt">${esc(x.excerpt||'')}</div><div class="why">${esc(why)}</div><a class="action" target="_blank" rel="noopener" href="${esc(x.url)}">Open official source ↗</a></div><div class="scores"><div class="scorebox main"><b>${x.research_fit}</b><span>RESEARCH FIT</span></div><div class="scorebox"><b>${x.paper1_score}</b><span>PAPER 1</span></div><div class="scorebox"><b>${x.paper2_score}</b><span>PAPER 2</span></div><div class="scorebox"><b>${x.trajectory_score}</b><span>TRAJECTORY</span></div><div class="scorebox"><b>${x.strategic_score}</b><span>PRIORITY</span></div></div></article>`}
function sup(){document.getElementById('supervisorList').innerHTML=S.sup.map(x=>{let sig=(x.opening_signals||[]).map(s=>`<span class="chip new">${esc(s)}</span>`).join(''),hits=(x.keyword_hits||[]).slice(0,7).map(s=>`<span class="chip">${esc(s)}</span>`).join('');return `<article class="card"><div><h3>${esc(x.name)}</h3><div class="meta">${esc(x.university)} · ${esc(x.country)}${x.city?' · '+esc(x.city):''} · profile ${x.page_ok?'reachable':'unreachable this scan'}</div><div class="chips">${sig}${hits}</div><div class="excerpt">${esc(x.excerpt||x.focus||'')}</div><a class="action" target="_blank" rel="noopener" href="${esc(x.url)}">Open profile ↗</a></div><div class="scores"><div class="scorebox main"><b>${x.research_fit}</b><span>RESEARCH FIT</span></div><div class="scorebox"><b>${x.paper1_score}</b><span>PAPER 1</span></div><div class="scorebox"><b>${x.paper2_score}</b><span>PAPER 2</span></div><div class="scorebox"><b>${x.strategic_score}</b><span>PRIORITY</span></div></div></article>`}).join('')}
function fund(){document.getElementById('fundingList').innerHTML=S.fund.map(x=>{let chips=[`<span class="chip ${x.funding==='Confirmed'?'funded':''}">${esc(x.funding)}</span>`,`<span class="chip">${esc(x.country)}</span>`];(x.funding_evidence||[]).slice(0,5).forEach(y=>chips.push(`<span class="chip">${esc(y)}</span>`));return `<article class="card"><div><h3>${esc(x.title)}</h3><div class="meta">${esc(x.university)} · ${fmt(x.deadline)}${(x.funding_amounts||[]).length?' · '+esc(x.funding_amounts.join(' · ')):''}</div><div class="chips">${chips.join('')}</div><div class="excerpt">${esc(x.excerpt||'')}</div><a class="action" target="_blank" rel="noopener" href="${esc(x.url)}">Open funding page ↗</a></div><div class="scores"><div class="scorebox main"><b>${x.score}</b><span>FUNDING PRIORITY</span></div></div></article>`}).join('')}
function status(){if(!S.status){document.getElementById('statusBody').textContent='No scan status yet.';return}let rows=(S.status.sources||[]).map(x=>`<tr><td>${esc(x.source)}</td><td>${esc(x.country)}</td><td class="${x.ok?'ok':'fail'}">${x.ok?'OK':'FAILED'}</td><td>${x.pages_fetched}</td><td>${x.matches}</td><td><a target="_blank" href="${esc(x.url)}">source</a></td></tr>`).join('');document.getElementById('statusBody').innerHTML=`<table class="status-table"><thead><tr><th>Source</th><th>Country</th><th>Status</th><th>Pages</th><th>Matches</th><th>Link</th></tr></thead><tbody>${rows}</tbody></table>`}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.panel').forEach(e=>e.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.tab).classList.add('active')});['search','country','fundingFilter','themeFilter','statusFilter','minFit'].forEach(id=>document.getElementById(id).addEventListener('input',opps));load();
