institutions:
  - name: University of Technology Sydney
    aliases: [UTS, University of Technology Sydney]
    country: Australia
    city: Sydney
    priority: 100
  - name: University of Sydney
    aliases: [University of Sydney, Sydney University]
    country: Australia
    city: Sydney
    priority: 96
  - name: UNSW Sydney
    aliases: [UNSW, University of New South Wales]
    country: Australia
    city: Sydney
    priority: 94
  - name: RMIT University
    aliases: [RMIT, RMIT University]
    country: Australia
    city: Melbourne
    priority: 90
  - name: Monash University
    aliases: [Monash, Monash University]
    country: Australia
    city: Melbourne
    priority: 88
  - name: University of Melbourne
    aliases: [University of Melbourne, Melbourne University]
    country: Australia
    city: Melbourne
    priority: 87
  - name: Wageningen University & Research
    aliases: [Wageningen University, Wageningen University & Research, WUR]
    country: Netherlands
    city: Wageningen
    priority: 97
  - name: Delft University of Technology
    aliases: [TU Delft, Delft University of Technology]
    country: Netherlands
    city: Delft
    priority: 90
  - name: Eindhoven University of Technology
    aliases: [TU/e, Eindhoven University of Technology]
    country: Netherlands
    city: Eindhoven
    priority: 84
  - name: University of Twente
    aliases: [University of Twente]
    country: Netherlands
    city: Enschede
    priority: 82
  - name: University of British Columbia
    aliases: [UBC, University of British Columbia]
    country: Canada
    city: Vancouver
    priority: 97
  - name: University of Toronto
    aliases: [University of Toronto, U of T]
    country: Canada
    city: Toronto
    priority: 95
  - name: University of Waterloo
    aliases: [University of Waterloo, Waterloo]
    country: Canada
    city: Waterloo
    priority: 88
  - name: HEC Montréal
    aliases: [HEC Montréal, HEC Montreal]
    country: Canada
    city: Montreal
    priority: 86
  - name: McGill University
    aliases: [McGill, McGill University]
    country: Canada
    city: Montreal
    priority: 88
  - name: Concordia University
    aliases: [Concordia, Concordia University]
    country: Canada
    city: Montreal
    priority: 80
  - name: Ontario Tech University
    aliases: [Ontario Tech, Ontario Tech University]
    country: Canada
    city: Oshawa
    priority: 74
