sources:
  - name: AcademicTransfer
    country: Netherlands
    url: https://www.academictransfer.com

  - name: University of Sydney
    country: Australia
    url: https://www.sydney.edu.au

  - name: UNSW
    country: Australia
    url: https://www.unsw.edu.au

  - name: UTS
    country: Australia
    url: https://www.uts.edu.au

  - name: Wageningen
    country: Netherlands
    url: https://www.wur.nl

  - name: TU Delft
    country: Netherlands
    url: https://www.tudelft.nl

  - name: UBC
    country: Canada
    url: https://www.ubc.ca
