sources:

  - name: University of Sydney
    country: Australia
    url: https://www.sydney.edu.au

  - name: UTS
    country: Australia
    url: https://www.uts.edu.au

  - name: UNSW Sydney
    country: Australia
    url: https://www.unsw.edu.au

  - name: RMIT University
    country: Australia
    url: https://www.rmit.edu.au

  - name: Monash University
    country: Australia
    url: https://www.monash.edu

  - name: Wageningen University
    country: Netherlands
    url: https://www.wur.nl

  - name: AcademicTransfer
    country: Netherlands
    url: https://www.academictransfer.com

  - name: UBC
    country: Canada
    url: https://www.ubc.ca

  - name: University of Waterloo
    country: Canada
    url: https://uwaterloo.ca

  - name: McGill University
    country: Canada
    url: https://www.mcgill.ca
